name: Node js-Devops-learning

on:
  push:
    branches: ['feature/docker-setup', 'develop', 'main']
  pull_request:
    branches: ['feature/docker-setup', 'develop', 'main']

jobs:
  build-and-test: # 👈 Job ID (Unique identifier)
    name: devops-learning-ci # Job Name (GitHub UI par dikhai dega)
    runs-on: ubuntu-latest   # Runner OS

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ya aapka Node.js version
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check Code Syntax / Linter (Optional)
        run: npm run lint --if-present

      # - name: Run Unit Tests (Agar tests hain)
      #   run: npm test