name: Nodejs-Api-Learn

'on':
    push:
        branches: ['feature/docker-setup', 'develop']
    
    pull_request:
        branches: ['feature/docker-setup', 'develop']

jobs:
    build-and-run:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis:alpine
                ports: 
                  - 6379:6379

        steps:
          - name: Checkout Reposetry
            uses: action/checkout@v4

          - name: Setup Node.js
            uses: action/setup-node@v4
            with:
                node-version: '22'
                cahce: npm

          - name: Install Dependencies
            run: npm ci

          - name: Check Code Syntax & Build
            run: node --check src/server.js
